#FROM nginx:stable-alpine

#RUN rm /etc/nginx/conf.d/default.conf

#COPY /include.websocket /etc/nginx/app/include.websocket
#COPY /include.forwarded /etc/nginx/app/include.forwarded
#COPY /nginx.conf /etc/nginx/conf.d
#COPY --from=brave-t-react /srv/app/build/ /usr/share/nginx/html

