apiVersion: v1
kind: ConfigMap
metadata:
  name: sql-config
  namespace: t5-dm
data:
  init.sql: |
    -- Create LapinPy core database
    CREATE database IF NOT EXISTS t5_core;
    GRANT ALL PRIVILEGES ON t5_core.* TO 't5'@'%';

    -- Create JAMO tape database
    CREATE database IF NOT EXISTS t5_tape;
    GRANT ALL PRIVILEGES ON t5_tape.* TO 't5'@'%';
  my.cnf: |
    [mysqld]
    sql-mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    log_bin_trust_function_creators = 1
