version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backendend-django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8001:8000
    env_file:
      - ./.env.dev
      - ./backend/.env
    volumes:
      - ./backend/:/srv/app
      - static:/srv/app/static
      - media:/srv/app/media
    depends_on:
      - db
  frontend: 
    build:
      context: ./frontend
    container_name: frontend-react
    #command: npm start
    ports:
      - 3001:3000
    env_file:
      - ./.env.dev
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    depends_on:
      - backend
  db:
    image: postgres:16.1-alpine
    container_name: dev-db
    ports:
      - 5432:5432
    env_file: ./.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
  nginx:
    build:
      context: ./frontend 
    container_name: nginx
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - frontend
      - backend
      - db


volumes:
  node_modules:
  postgres_data:
  media:
  static:
