apiVersion: apps/v1
kind: Deployment
metadata:
  name: jamo-mysql
  namespace: t5-dm
spec:
      name: jamo-mysql
      namespace: t5-dm
    spec:
      containers:
        - env:
            - name: MYSQL_USER
              value: t5
            - name: MYSQL_PASSWORD_FILE
              value: /secrets/password
            - name: MYSQL_DATABASE
              value: t5_core
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: 'yes'
            - name: TZ
              value: America/Los_Angeles
          image: mysql:8
          imagePullPolicy: Always
          name: mysql
          ports:
            - containerPort: 3306
              name: mysql
              protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - CHOWN
                - DAC_OVERRIDE
                - FOWNER
                - SETGID
                - SETUID
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: vol-db-data
            - mountPath: /secrets
              name: vol-db-pass
            - mountPath: /etc/mysql/conf.d/my.cnf
              name: vol-db-conf
              subPath: my.cnf
            - mountPath: /docker-entrypoint-initdb.d/init.sql
              name: vol-db-conf
              subPath: init.sql
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: vol-db-data
          persistentVolumeClaim:
            claimName: jamo-mysql
        - name: vol-db-pass
          secret:
            defaultMode: 420
            secretName: jamo-mysql-pass
        - configMap:
            defaultMode: 420
            name: sql-config
          name: vol-db-conf
