

services:
  django-prod:
    build: ./backend
    container_name: django-prod
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8001:8000
    env_file:
      - ./.env.dev
      - ./backend/.env
    volumes:
      - ./backend/:/srv/app
      - static:/srv/app/static
      - media:/srv/app/media
    depends_on:
      - db
  react-prod:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    container_name: react-prod
    command: npm start
    ports:
      - 3001:3000
    env_file:
      - ./.env.dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - django-prod
  db-prod:
    image: postgres:16.1-alpine
    container_name: db-prod
    ports:
      - 5432:5432
    env_file: ./.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
  nginx-prod:
    build: ./nginx
    container_name: nginx-prod
    ports:
      - 8080:80
    restart: always
    volumes:
      - static:/srv/app/static
      - media:/srv/app/media
    depends_on:
      - django-prod
      - react-prod
      - db-prod

volumes:
  node_modules:
  postgres_data:
  media:
  static:
