services:
  django:
    build: ./backend
    container_name: django-prod
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8001:8000
    env_file:
      - ./.env.dev
      - ./backend/.env
    volumes:
      - ./backend/:/srv/app
      - static:/srv/app/static
      - media:/srv/app/media
    depends_on:
      - db

  react:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: react-prod
    command: npm start
    ports:
      - 3000:3000
    env_file:
      - ./.env.dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - django

  db:
    image: postgres:16.1-alpine
    container_name: db-prod
    ports:
      - 5432:5432
    env_file: ./.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    container_name: nginx-prod
    ports:
      - 8080:80
    restart: always
    volumes:
      - static:/srv/app/static
      - media:/srv/app/media
    depends_on:
      - django
      - react
      - db

volumes:
  # node_modules:
  postgres_data:
  media:
  static:
