apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jamo-mysql
  namespace: t5-dm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client
  volumeMode: Filesystem
