name: Build and Deploy

on:
  push:
    branches: [ main ]
    paths:
      - "data_management/jamo/jamo/**"
      - "data_management/jamo/jat/**"
      - "data_management/jamo/lapinpy/**"
      - "data_management/jamo/sdm-common/**"

jobs:
  deploy-container:
    runs-on: ubuntu-latest
    environment: JAMO_DEPLOY
    env:
      KUBECONFIG: /tmp/kubeconfig

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to registry
      uses: docker/login-action@v3
      with:
        registry: registry.nersc.gov
        username: ${{ vars.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: data_management/jamo
        platforms: linux/amd64
        push: true
        tags: |
          registry.nersc.gov/m4521/jamo-service:${{ github.sha }}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" | base64 -d > $KUBECONFIG

    - name: Update image for JAMO deployment and set change-cause
      run: |
        kubectl set image deployment/jamo-app lapin-app=registry.nersc.gov/m4521/jamo-service:${{ github.sha }}
        kubectl annotate deployment jamo-app kubectl.kubernetes.io/change-cause="Updated image to ${{ github.sha }}" --overwrite

    - name: Wait for rollout to finish
      id: rollout_status
      run: |
        kubectl rollout status deployment/jamo-app
      continue-on-error: true

    - name: Rollback on failure
      if: steps.rollout_status.outcome == 'failure'
      run: |
        echo "Rollout failed, rolling back..."
        kubectl rollout undo deployment/jamo-app
